### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by denniskai1234** [chancity/BotManager#10]
When i start the manager i get this error:

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path)
   bei BotManager.UserInterface.Downloading.NecroMoboReadSettings(SupportedBotInformation& supportedBotInformation) in C:\Users\Administrator\Desktop\bot3\botmanager\UserInterface\Downloading.vb:Zeile 176.
   bei BotManager.UserInterface.Downloading.AddSettings(SupportedBotInformation& supportedBotInformation) in C:\Users\Administrator\Desktop\bot3\botmanager\UserInterface\Downloading.vb:Zeile 167.
   bei BotManager.UserInterface.Downloading.BackgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\Administrator\Desktop\bot3\botmanager\UserInterface\Downloading.vb:Zeile 43.
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Any solution for this?

**Comment by Brewfasa** [comment]
Same here, the appdata/botmanager folder seems to get cleared after closing the botmanager.exe and when you try to start it again on relaunching botmanager, it simply cant find the settings and results in that error... 

Isn't it possible to just save those settings in the folder that botmanager is actually in?

**Comment by chancity** [comment]
This issue is fixed now
