### ISSUE TITLE
[Request] Autostart

### ISSUE THREAD

**Issue by Nestade** [chancity/BotManager#3]
Hey,

Could you add an option to add it into autostart?
At the moment it's not possible because it's asking you if you want to download the newest version so it won't start.

Also it would be cool if it would be possible that it uses the same PokemonsToEvolve list after every restart.

Thanks in advance! :)

Regards,
Nestade

**Comment by chancity** [comment]
I'll start working on that today :D.

**Comment by chancity** [comment]
Just click No when asked to update!

**Comment by Nestade** [comment]
Thanks :)
Well - I'm running it on my dedicated server and would like to autostart it (in case my server restarts).
But you did an awesome job - I really like the BotManager :)
