### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Nestade** [chancity/BotManager#5]
Hello,

I'm getting the following errors when I try to compile:
`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Warnung		Die Komponente "Newtonsoft.Json", auf die verwiesen wird, wurde nicht gefunden.	BotManager			
`

```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	BC30002	Der Typ "JObject" ist nicht definiert.	BotManager	D:\PokemonGo\Botmanager\botmanager\Manager\Necro.vb	23	Aktiv
Fehler	BC30456	"JObject" ist kein Member von "System.Linq".	BotManager	D:\PokemonGo\Botmanager\botmanager\Manager\Necro.vb	23	Aktiv
Fehler	BC30002	Der Typ "JObject" ist nicht definiert.	BotManager	D:\PokemonGo\Botmanager\botmanager\Manager\Necro.vb	24	Aktiv
Fehler	BC30456	"JObject" ist kein Member von "System.Linq".	BotManager	D:\PokemonGo\Botmanager\botmanager\Manager\Necro.vb	24	Aktiv
Fehler	BC30002	Der Typ "JObject" ist nicht definiert.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	173	Aktiv
Fehler	BC30456	"JObject" ist kein Member von "System.Linq".	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	173	Aktiv
Fehler	BC30002	Der Typ "JObject" ist nicht definiert.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	174	Aktiv
Fehler	BC30456	"JObject" ist kein Member von "System.Linq".	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	174	Aktiv
Fehler	BC30002	Der Typ "JProperty" ist nicht definiert.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	176	Aktiv
Fehler	BC30002	Der Typ "JProperty" ist nicht definiert.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	182	Aktiv
Warnung	BC40056	Der in Imports "Newtonsoft.Json.Linq" angegebene Namespace oder Typ enthält keine öffentlichen Member oder kann nicht gefunden werden. Stellen Sie sicher, dass der Namespace oder der Typ definiert ist und mindestens einen öffentlichen Member enthält, und dass der importierte Elementname keine Aliase verwendet.	BotManager	D:\PokemonGo\Botmanager\botmanager\Manager\Necro.vb	2	Aktiv
Warnung	BC40056	Der in Imports "Newtonsoft.Json" angegebene Namespace oder Typ enthält keine öffentlichen Member oder kann nicht gefunden werden. Stellen Sie sicher, dass der Namespace oder der Typ definiert ist und mindestens einen öffentlichen Member enthält, und dass der importierte Elementname keine Aliase verwendet.	BotManager	D:\PokemonGo\Botmanager\botmanager\Manager\Necro.vb	3	Aktiv
Warnung	BC40056	Der in Imports "Newtonsoft.Json" angegebene Namespace oder Typ enthält keine öffentlichen Member oder kann nicht gefunden werden. Stellen Sie sicher, dass der Namespace oder der Typ definiert ist und mindestens einen öffentlichen Member enthält, und dass der importierte Elementname keine Aliase verwendet.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	6	Aktiv
Warnung	BC40056	Der in Imports "Newtonsoft.Json.Converters" angegebene Namespace oder Typ enthält keine öffentlichen Member oder kann nicht gefunden werden. Stellen Sie sicher, dass der Namespace oder der Typ definiert ist und mindestens einen öffentlichen Member enthält, und dass der importierte Elementname keine Aliase verwendet.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	7	Aktiv
Warnung	BC40056	Der in Imports "Newtonsoft.Json.Linq" angegebene Namespace oder Typ enthält keine öffentlichen Member oder kann nicht gefunden werden. Stellen Sie sicher, dass der Namespace oder der Typ definiert ist und mindestens einen öffentlichen Member enthält, und dass der importierte Elementname keine Aliase verwendet.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	8	Aktiv
Warnung	BC40056	Der in Imports "Newtonsoft.Json.Serialization" angegebene Namespace oder Typ enthält keine öffentlichen Member oder kann nicht gefunden werden. Stellen Sie sicher, dass der Namespace oder der Typ definiert ist und mindestens einen öffentlichen Member enthält, und dass der importierte Elementname keine Aliase verwendet.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Downloading.vb	9	Aktiv
Warnung	BC42104	Die parts-Variable wird verwendet, bevor ihr ein Wert zugewiesen wird. Zur Laufzeit kann eine Nullverweisausnahme auftreten.	BotManager	D:\PokemonGo\Botmanager\botmanager\UserInterface\Main.vb	179	Aktiv
Warnung		Dieser Verweis konnte nicht aufgelöst werden. Die Newtonsoft.Json-Assembly wurde nicht gefunden. Stellen Sie sicher, dass die Assembly auf dem Datenträger vorhanden ist. Falls dieser Verweis im Code erforderlich ist, können Kompilierungsfehler auftreten.	BotManager			

```

Sorry, I'll download the English version of VS2015 now and post the error in English.

Regards,
Nestade

**Comment by Nestade** [comment]
This are the errors in English:

`Severity	Code	Description	Project	File	Line	Suppression State
Warning		Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	BotManager			
Error	BC30002	Type 'JObject' is not defined.	BotManager	D:\PokemonGo\BotManager-master\botmanager\Manager\Necro.vb	23	Active
Error	BC30456	'JObject' is not a member of 'System.Linq'.	BotManager	D:\PokemonGo\BotManager-master\botmanager\Manager\Necro.vb	23	Active
Error	BC30002	Type 'JObject' is not defined.	BotManager	D:\PokemonGo\BotManager-master\botmanager\Manager\Necro.vb	24	Active
Error	BC30456	'JObject' is not a member of 'System.Linq'.	BotManager	D:\PokemonGo\BotManager-master\botmanager\Manager\Necro.vb	24	Active
Error	BC30002	Type 'JObject' is not defined.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	173	Active
Error	BC30456	'JObject' is not a member of 'System.Linq'.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	173	Active
Error	BC30002	Type 'JObject' is not defined.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	174	Active
Error	BC30456	'JObject' is not a member of 'System.Linq'.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	174	Active
Error	BC30002	Type 'JProperty' is not defined.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	176	Active
Error	BC30002	Type 'JProperty' is not defined.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	182	Active
Warning	BC40056	Namespace or type specified in the Imports 'Newtonsoft.Json.Linq' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	BotManager	D:\PokemonGo\BotManager-master\botmanager\Manager\Necro.vb	2	Active
Warning	BC40056	Namespace or type specified in the Imports 'Newtonsoft.Json' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	BotManager	D:\PokemonGo\BotManager-master\botmanager\Manager\Necro.vb	3	Active
Warning	BC40056	Namespace or type specified in the Imports 'Newtonsoft.Json' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	6	Active
Warning	BC40056	Namespace or type specified in the Imports 'Newtonsoft.Json.Converters' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	7	Active
Warning	BC40056	Namespace or type specified in the Imports 'Newtonsoft.Json.Linq' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	8	Active
Warning	BC40056	Namespace or type specified in the Imports 'Newtonsoft.Json.Serialization' doesn't contain any public member or cannot be found. Make sure the namespace or the type is defined and contains at least one public member. Make sure the imported element name doesn't use any aliases.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Downloading.vb	9	Active
Warning	BC42104	Variable 'parts' is used before it has been assigned a value. A null reference exception could result at runtime.	BotManager	D:\PokemonGo\BotManager-master\botmanager\UserInterface\Main.vb	179	Active
Warning		The referenced component 'Newtonsoft.Json' could not be found.	BotManager			
`

**Comment by Nestade** [comment]
Seems to be a problem with necro

**Comment by chancity** [comment]
Add the Newton library into the directory that the bot manager is running.

**Comment by Nestade** [comment]
Thanks - it worked now - just had to compile Necro by hand.
By the way - could you add PokeMobBot instead of Necro, please?

Regards,
Nestade
